"""removed dl_status

Revision ID: 05693e86579f
Revises: a73edcf1fd42
Create Date: 2024-01-11 21:45:01.122595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05693e86579f'
down_revision = 'a73edcf1fd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.drop_column('dl_status')

    with op.batch_alter_table('image_file', schema=None) as batch_op:
        batch_op.drop_column('dl_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dl_status', sa.VARCHAR(length=200), nullable=False))

    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dl_status', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
