"""Add download handler

Revision ID: a73edcf1fd42
Revises: 79873af71a76
Create Date: 2024-01-08 17:09:01.245471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73edcf1fd42'
down_revision = '79873af71a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['song_meta_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dl_status', sa.String(length=200), nullable=False))

    with op.batch_alter_table('image_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dl_status', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_file', schema=None) as batch_op:
        batch_op.drop_column('dl_status')

    with op.batch_alter_table('audio_file', schema=None) as batch_op:
        batch_op.drop_column('dl_status')

    op.drop_table('download_queue')
    # ### end Alembic commands ###
