"""empty message

Revision ID: fc019d4d0b85
Revises: 
Create Date: 2023-09-15 17:05:14.970692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc019d4d0b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('extension', sa.String(length=200), nullable=False),
    sa.Column('audio_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('extension', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yt_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_publisher', sa.Integer(), nullable=True),
    sa.Column('yt_title', sa.String(length=200), nullable=True),
    sa.Column('yt_description', sa.String(length=200), nullable=True),
    sa.Column('yt_id', sa.String(length=200), nullable=False),
    sa.Column('yt_data_raw', sa.String(length=10000), nullable=True),
    sa.Column('file_id_audio', sa.Integer(), nullable=True),
    sa.Column('file_id_image', sa.Integer(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id_audio'], ['audio_file.id'], ),
    sa.ForeignKeyConstraint(['file_id_image'], ['image_file.id'], ),
    sa.ForeignKeyConstraint(['id_publisher'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id_audio'),
    sa.UniqueConstraint('file_id_image')
    )
    op.create_table('song_user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_data_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('extras', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['meta_data_id'], ['song_meta_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_song',
    sa.Column('user_data_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_data_id'], ['song_user_data.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_song')
    op.drop_table('song_user_data')
    op.drop_table('song_meta_data')
    op.drop_table('publisher')
    op.drop_table('image_file')
    op.drop_table('audio_file')
    op.drop_table('artist')
    # ### end Alembic commands ###
